name: carnd-semseg
channels:
    - defaults
dependencies:
    - python=3.6
    - scipy
    - pillow
    - numpy
    - matplotlib
    - jupyter
    - ffmpeg
    - imageio
    - cudatoolkit==8.0
    - cudnn==6.0
    - opencv3
    - plotly
    - numba
    - pip:
        - protobuf==3.4.0
        - moviepy
        - tensorflow-gpu==1.4
        - tensorflow-tensorboard==0.4.0
